### ISSUE TITLE
Automatically apply python code styling (black)

### ISSUE THREAD

**Issue by wakamezake** [stanfordmlgroup/ngboost#90]
I often see [commit for code cleanup](https://github.com/stanfordmlgroup/ngboost/search?q=clean&type=Commits).
I think it is better to automatically apply python code styling.

- [pre-commit](https://pre-commit.com/)
- [black](https://github.com/psf/black)

**Comment by alejandroschuler** [comment]
hey @wakamezake, thanks for these suggestions! Right now I have CI set up through GH actions (as I think you suggested a while back) and it uses the default python package workflow (linting and testing). Are you suggesting pre-commit checks in addition to the CI? Or can we just add black to the CI? If you send me a workflow script I can switch out what we have. Right now it's:

```
name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
```
